### PR TITLE
Changed usage of MouseEvent.which to MouseEvent.button

### PR DESCRIPTION
**Pull request by andrey-zakharov**

### CODE REVIEW

**Comment by zoechi** [comment]
Andrey, thanks a lot for the PR. Did you actually test this is working?
When I made the change in the polymer1 branch, I discovered that the button numbers start with `0` instead of `1` (when `button` is used instead of `which´)

closes #151

**Comment by andrey-zakharov** [comment]
I've tested only resizing of columns. Always use named constants if its possible :)
From reference:
> The value of the button attribute MUST be as follows:
> 
> 0 MUST indicate the primary button of the device (in general, the left button or the only button on single-button devices, used to activate a user interface control or select text) or the un-initialized value.
> 
> 1 MUST indicate the auxiliary button (in general, the middle button, often combined with a mouse wheel).
> 
> 2 MUST indicate the secondary button (in general, the right button, often used to display a context menu).

https://w3c.github.io/uievents/#interface-mouseevent

**Comment by zoechi** [comment]
> Always use named constants if its possible :)

You are right of course.

**Comment by zoechi** [comment]
Merged and published an update.

**Comment by zoechi** [comment]
Thanks again for the PR :)

**Pull request merged**
